### ISSUE TITLE
build problem: gettext version mismatch

### ISSUE THREAD

**Issue by tiborh** [alessio/camorama#32]
make[3]: Leaving directory '{path cut out}camorama/po'
*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.19 but the autoconf macros are from gettext version 0.20
[2]: *** [Makefile:235: stamp-po] Error 1
make[2]: Leaving directory '{}camorama/po'
make[1]: *** [Makefile:531: all-recursive] Error 1
make[1]: Leaving directory '{}camorama'
make: *** [Makefile:387: all] Error 2

**Comment by tiborh** [comment]
workaround:
in
camorama/po/Makefile
line 10:
original:
GETTEXT_MACRO_VERSION = 0.19
modified:
GETTEXT_MACRO_VERSION = 0.20
make runs, compilation finishes. camera software is installed. program runs.

**Comment by mchehab** [comment]
> workaround:
> in
> camorama/po/Makefile
> line 10:
> original:
> GETTEXT_MACRO_VERSION = 0.19
> modified:
> GETTEXT_MACRO_VERSION = 0.20
> make runs, compilation finishes. camera software is installable. program runs.

The right fix would be, instead, to run:
```
   $ gettextize
```

This will update gettext to version 0.20, as shown in this patch:
https://github.com/mchehab/camorama/commit/7af316bde3407d06d8945f2de2d3df00ab17723f

**Comment by mchehab** [comment]
Did some changes there, as otherwise it will still fail on some platforms. Basically, I removed the dependency of an specific gettext version and cleaned the auto-generated files.

The build is now done by:
```
./autogen.sh
#optionally, ./configure
make
```

That will require `autotools` to be installed, but that's the normal case nowadays.

**Comment by Hannes-III** [comment]
Today I was using Head from Master (13 Mar) and still had that Problem.
I used `gettextize`, but had to use 

    $ gettextize -f

to make it work.
