### ISSUE TITLE
Please add AppData File

### ISSUE THREAD

**Issue by Jibec** [alessio/camorama#4]
Hi, I'm a translator from Fedora. I would like your software to be translated in Gnome-Software.

To do this, please add this appdata file to your project (it's basically an improved .desktop file, you may have a look on appstream or appdata on freedesktop) :
http://pkgs.fedoraproject.org/cgit/rpms/camorama.git/tree/camorama.appdata.xml?h=f24

Then, please update your po files : one blog post about it https://blogs.gnome.org/mclasen/2016/07/21/using-modern-gettext/

Then, tell me where to go to translate ;)

thanks for your help

**Comment by alessio** [comment]
Please open a PR. Thanks

**Comment by mchehab** [comment]
Appdata and automatic po files updates added on Camorama 0.20. Please let us know if you find any issues with translations.
