### ISSUE TITLE
Please change Build Section in Readme.md

### ISSUE THREAD

**Issue by Hannes-III** [alessio/camorama#42]
My Distro unfortunately does not provide packages for camorama, so I had to build it on my own.
I took some time and headache to get it done because the build process was not so easy as promised in Readme.md.
Please update this section. My experience was:
```bash
sudo apt-get install gnome-common libv4l-dev libcairo2-dev libgtk-3-dev

unzip camorama-master.zip
cd camorama-master/
gettextize -f
aclocal -I m4
./autogen.sh
make
echo $?
sudo make install
```

Thank you, this will help others too to use this cool tool.
I use it every Christmas to make a time-lapse Video while I trim the Christmas tree.

**Comment by mchehab** [comment]
readme updated with the current install instructions.
