### ISSUE TITLE
Suggested config file addition

### ISSUE THREAD

**Issue by sww724** [alessio/camorama#6]
If two cameras are on the system, you cannot access the second one - no user interface to do so. I also have a complaint: if the first device is already in use, camorama bails out without any explanation, just a brief blip on the screen and gone.  I would like to see camorama scan the available video devices and gracefully skip any nonexistant or in use devices.  It would also be nice to specify an exact camera to use in case of multiple cameras, and make that choice persistent through the config file so that it is the default camera each time camorama starts, if it is available.  If no devices are available, an advisory message to that effect would be appreciated rather than just bailing out.

**Comment by mchehab** [comment]
Pull Request #27 (and a few previous changes) addresses this issue: now, when camorama is started first time and it has multiple cameras (or when it tries to open an invalid device), a dialog will popup asking to select the camera. It will then be stored, together with the latest preferred resolution. This way, when started again, it will use the last device and resolution. 

Such dialog is also visible when multiple cameras were detected at Camorama's startup, allowing to switch between the cameras at runtime.
