### ISSUE TITLE
Date and time color is a problem

### ISSUE THREAD

**Issue by Plutonium5793** [alessio/camorama#7]
I just downloaded and compiled camorama-master and am using it to monitor a camera and send an photo up to a weather internet site every 5 minutes.  It also saves a copy to hard drive.  The borders on both images are black.  On the image saved to the hard drive, the lettering is either yellow or white on black. On the image uploaded the lettering is black on black and can barely be seen and not read. I don't know how the color is chosen but something is wrong.

**Comment by mchehab** [comment]
The logic used to store images were rewritten. Please try again against upstream version.
