### ISSUE TITLE
Under Raspberry pi, camorama is producing false color images

### ISSUE THREAD

**Issue by Plutonium5793** [alessio/camorama#8]
I compiled the current version of camorama-master under raspian on a Rpi.  It finds the camera, but the image display is way too intense with saturated colors.  half of the image is white.  The camera is working well under windows,and fedora linux.

**Comment by mchehab** [comment]
I'm closing this issue, due to the lack of news about it. If this is still reproducible with recent Kernels, please re-open and provide more details about what camera(s) are causing issues with Camorama.
